<?php

/**
 * @file
 * Contains hook implementations.
 */

/**
 * Implements hook_mail_alter().
 */
function email_formatter_mail_alter(&$message) {
  $message['headers']['Content-Type'] = "text/html; charset=UTF-8;format=flowed;delsp=yes";

  /** @var \Drupal\email_formatter\EmailFormatter\PluginManagerInterface $plugin_manager */
  $plugin_manager = \Drupal::service('plugin.manager.email_formatter');
  $definitions = $plugin_manager->getEmailFormatters($message['id']);
  foreach ($definitions as $definition) {
    /** @var \Drupal\email_formatter\EmailFormatter\EmailFormatterPluginBase $definition */
    $message = $definition->formatMessage($message);
  }
}

/**
 * Implements hook_theme().
 */
function email_formatter_theme($existing, $type, $theme, $path) {
  $themes = [];
  $plugin_manager = \Drupal::service('plugin.manager.email_formatter');
  $definitions = $plugin_manager->getDefinitions();
  foreach ($definitions as $definition) {
    if (isset($definition['themeKey'])) {
      $themes[$definition['themeKey']] = [
        'variables' => [
          'email_variables' => NULL,
        ],
        'path' => drupal_get_path('module', $definition['provider']) . '/templates',
      ];
    }
  }

  return $themes;
}
